default:
  image: node:lts

stages:
  - deploy

deploy_staging:
  stage: deploy
  script:
    - echo "Installing dependencies"
    - npm install
    - echo "Building the app"
    - npm run build
    - echo "Artifacts created at ./build/"
  only:
  - master
  - devel
  artifacts:
    paths:
    - ./build/
    expire_in: 1 week

