default:
  image: node:lts

stages:
  - build

build_artifacts:
  stage: build
  script:
    - echo "Installing dependencies"
    - npm install
    - echo "Building the app"
    - npm run build
    - echo "Generating single file at ./build/"
    - npx gulp
  only:
  - master
  - devel
  artifacts:
    paths:
    - ./build/index.html
    expire_in: 1 week

