default:
  image: node:lts

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: 
    - echo "Running tests"
    - echo "No tests to run"

build:
  stage: build
  script:
    - echo "Building the app"
    - echo "npm run-script build"
    - npm install
    - npm run-script build
  artifacts:
    paths:
    - build/
    expire_in: 1 week

deploy_review:
  stage: deploy
  script:
    - echo "Deploy a review app"
    - echo "Copying files to production server using scp"
    - scp -i $SSH_DEPLOY_KEY -o UserKnownHostsFile=./ssh_config/known_hosts -r -P 7890 ./build/* gitlab@armyadmintools.com:/var/www/html/timewise/
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.armyadmintools.com
  only:
    - branches
  except:
    - master

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: https://armyadmintools.com/staging/
  only:
  - master

deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production server"
    - echo "Copying files to production server using scp"
    - scp -i $SSH_DEPLOY_KEY -o UserKnownHostsFile=./ssh_config/known_hosts -r -P 7890 ./build/* gitlab@armyadmintools.com:/var/www/html/timewise/
  environment:
    name: production
    url: https://armyadmintools.com/
  when: manual
  only:
  - master
  - devel